- hosts: all
#   become: true

  tasks:
  - name: create a docker image with deployed war file
    command: docker build -t jch941022/cicd-project-ansible .
    args: 
        chdir: /root
    
  - name: push the image on Docker Hub
    command: docker push jch941022/cicd-project-ansible

  - name: remove the docker image from the ansible server
    command: docker rmi jch941022/cicd-project-ansible  
    ignore_errors: yes
